data = [
  {"github.com" = "Genida/archan", "gitlab.com" = "icube-cstb/archan"},
  {"github.com" = "Genida/dependenpy", "gitlab.com" = "icube-cstb/dependenpy"},
  {"github.com" = "Genida/django-appsettings", "gitlab.com" = "pawamoy/django-appsettings"},
  {"github.com" = "Genida/django-cerberus-ac", "gitlab.com" = "icube-cstb/django-cerberus-ac"},
  {"github.com" = "Genida/django-cs-models", "gitlab.com" = "icube-cstb/django-cs-models"},
  {"github.com" = "Genida/django-meerkat", "gitlab.com" = "icube-cstb/django-meerkat"},
  {"github.com" = "shellm-org/daemon", "gitlab.com" = "shellm/daemon"},
  {"github.com" = "shellm-org/data", "gitlab.com" = "shellm/data"},
  {"github.com" = "shellm-org/debug", "gitlab.com" = "shellm/debug"},
  {"github.com" = "shellm-org/format", "gitlab.com" = "shellm/format"},
  {"github.com" = "shellm-org/loadtime", "gitlab.com" = "shellm/loadtime"},
  {"github.com" = "shellm-org/loop", "gitlab.com" = "shellm/loop"},
  {"github.com" = "shellm-org/new", "gitlab.com" = "shellm/neww"},
  {"github.com" = "shellm-org/oldlibs", "gitlab.com" = "shellm/oldlibs"},
  {"github.com" = "shellm-org/preload", "gitlab.com" = "shellm/preload"},
  {"github.com" = "shellm-org/project", "gitlab.com" = "shellm/project"},
  {"github.com" = "shellm-org/require", "gitlab.com" = "shellm/require"},
  {"github.com" = "shellm-org/shellm", "gitlab.com" = "shellm/shellm"},
  {"github.com" = "shellm-org/shellman", "gitlab.com" = "shellm/shellman"},
  {"github.com" = "shenv/shenv.github.io", "gitlab.com" = "shenv/shen.gitlab.io"},
]
